spring.application.name=streakflow

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/streakflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:streakflow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:streakflow}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
